### ISSUE TITLE
11차 코딩스터디 (3/1~3/5)

### ISSUE THREAD

**Issue by inbdni** [LeeSeoYoung012/CodingStudy#11]
# 11차 코딩스터디 (3/1~3/5)

## 3/1 월요일

삼일절

## 3/2 화요일

* Level 3 합승 택시 요금 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/72413)
* Level 3 하노이의 탑 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12946)
* 2x2x2 큐브 [[Link]](https://www.acmicpc.net/problem/16939)

## 3/3 수요일

* Level 3 징검다리 건너기 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/64062)
* Level 3 N-Queen [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12952)
* 레벨 햄버거 [[Link]](https://www.acmicpc.net/problem/16974)

## 3/4 목요일

* Level 3 보석 쇼핑 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/67258)
* Level 3 배달 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12978)
* 벽 부수고 이동하기 4 [[Link]](https://www.acmicpc.net/problem/16946)

## 3/5 금요일

* Level 3 경주로 건설 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/67259)
* Level 3 기지국 설치 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12979)
* 벽 부수고 이동하기 2 [[Link]](https://www.acmicpc.net/problem/14442)

**Comment by inbdni** [comment]
3/2 화요일 완료했습니다.

* [합승 택시 요금](https://github.com/inbdni/Programmers/blob/master/level03/%ED%95%A9%EC%8A%B9%ED%83%9D%EC%8B%9C%EC%9A%94%EA%B8%88.cpp)
* [하노이의 탑](https://github.com/inbdni/Programmers/blob/master/level03/%ED%95%98%EB%85%B8%EC%9D%B4%EC%9D%98%ED%83%91.cpp)
* [2x2x2 큐브](https://github.com/inbdni/Baekjoon/blob/master/16939_2X2X2%ED%81%90%EB%B8%8C.cpp)

**Comment by inbdni** [comment]
3/3 수요일 완료했습니다.

* [징검다리 건너기](https://github.com/inbdni/Programmers/blob/master/level03/%EC%A7%95%EA%B2%80%EB%8B%A4%EB%A6%AC%EA%B1%B4%EB%84%88%EA%B8%B0.cpp)
* [N-Queen](https://github.com/inbdni/Programmers/blob/master/level03/N-Queen.cpp)
* [레벨 햄버거](https://github.com/inbdni/Baekjoon/blob/master/16974_%EB%A0%88%EB%B2%A8%ED%96%84%EB%B2%84%EA%B1%B0.cpp)

**Comment by Jiyoung-h** [comment]
3/2 화요일 완료했습니다.
- [합승 택시 요금](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%ED%95%A9%EC%8A%B9%20%ED%83%9D%EC%8B%9C%20%EC%9A%94%EA%B8%88.cpp)
- [하노이의 탑](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%ED%95%98%EB%85%B8%EC%9D%B4%EC%9D%98%20%ED%83%91.cpp)
- [2x2x2 큐브](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16939%202x2x2%20%ED%81%90%EB%B8%8C.cpp)

**Comment by LeeSeoYoung012** [comment]
3/2 화요일 완료했습니다.

- [합승 택시 요금](https://spacefordeveloper.tistory.com/236)
- [하노이의 탑](https://spacefordeveloper.tistory.com/235)
- 2x2x2 큐브- 미해결

**Comment by dongwonnn** [comment]
3/2일 화요일 완료했습니다.

- [합승 택시 요금](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%ED%95%98%EB%85%B8%EC%9D%B4.md)
- [하노이의 탑](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%ED%95%98%EB%85%B8%EC%9D%B4.md)
- 2x2x2 큐브( 미해결 )

**Comment by Jiyoung-h** [comment]
3/3 수요일 완료했습니다.
- [징검다리 건너기](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%A7%95%EA%B2%80%EB%8B%A4%EB%A6%AC.cpp)
- [N-Queen](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/N-Queen.cpp)
- [레벨 햄버거](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16974%20%EB%A0%88%EB%B2%A8%20%ED%96%84%EB%B2%84%EA%B1%B0.cpp)

**Comment by dongwonnn** [comment]
3/3 수요일 완료했습니다.

- [징검다리 건너기](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%A7%95%EA%B2%80%EB%8B%A4%EB%A6%AC%20%EA%B1%B4%EB%84%88%EA%B8%B0.md)
- N-Queen ( 진행중 )
- [레벨 햄버거](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EB%A0%88%EB%B2%A8%20%ED%96%84%EB%B2%84%EA%B1%B0.md)

**Comment by Jiyoung-h** [comment]
3/4 목요일
- [보석 쇼핑](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%B3%B4%EC%84%9D%20%EC%87%BC%ED%95%91.cpp)
- [배달](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%B0%B0%EB%8B%AC.cpp)
- [벽 부수고 이동하기 4](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16946%20%EB%B2%BD%20%EB%B6%80%EC%88%98%EA%B3%A0%20%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B04.cpp)

**Comment by inbdni** [comment]
3/4 목요일 완료했습니다.

* [보석 쇼핑](https://github.com/inbdni/Programmers/blob/master/level03/%EB%B3%B4%EC%84%9D%EC%87%BC%ED%95%91.cpp)
* [배달](https://github.com/inbdni/Programmers/blob/master/level03/%EB%B0%B0%EB%8B%AC.cpp)
* [벽 부수고 이동하기 4](https://github.com/inbdni/Baekjoon/blob/master/16946_%EB%B2%BD%EB%B6%80%EC%88%98%EA%B3%A0%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B04.cpp)

**Comment by LeeSeoYoung012** [comment]
3/3 수요일 완료했습니다.

- [징검다리 건너기](https://spacefordeveloper.tistory.com/241)
- [N-Queen](https://spacefordeveloper.tistory.com/240)
- [레벨 햄버거](https://spacefordeveloper.tistory.com/242)

**Comment by LeeSeoYoung012** [comment]
3/4 목요일 완료했습니다.

- [보석 쇼핑](https://spacefordeveloper.tistory.com/238?category=967186)
- [배달](https://spacefordeveloper.tistory.com/239?category=934246)
- [벽 부수고 이동하기 4 - 진행중]

**Comment by dongwonnn** [comment]
3/4 목요일 완료했습니다.

- [보석 쇼핑](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%B3%B4%EC%84%9D%20%EC%87%BC%ED%95%91.md)
- [배달](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%B0%B0%EB%8B%AC.md)
- 벽 부수고 이동하기 4 - 진행중

**Comment by Jiyoung-h** [comment]
3/5 금요일 완료했습니다.
- [경주로 건설](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EA%B2%BD%EC%A3%BC%EB%A1%9C.cpp)
- [기지국 설치](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EA%B8%B0%EC%A7%80%EA%B5%AD%20%EC%84%A4%EC%B9%98.cpp)
- [벽 부수고 이동하기 2](url)

**Comment by inbdni** [comment]
3/5 금요일 완료했습니다.

* [경주로 건설](https://github.com/inbdni/Programmers/blob/master/level03/%EA%B2%BD%EC%A3%BC%EB%A1%9C%EA%B1%B4%EC%84%A4.cpp)
* [기지국 설치](https://github.com/inbdni/Programmers/blob/master/level03/%EA%B8%B0%EC%A7%80%EA%B5%AD%EC%84%A4%EC%B9%98.cpp)
* [벽 부수고 이동하기 2](https://github.com/inbdni/Baekjoon/blob/master/14442_%EB%B2%BD%EB%B6%80%EC%88%98%EA%B3%A0%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B02.cpp)

**Comment by LeeSeoYoung012** [comment]
3/5 금요일 완료했습니다.
- [경주로 건설](https://spacefordeveloper.tistory.com/244)
- [기지국 설치](https://spacefordeveloper.tistory.com/245)
- [벽 부수고 이동하기 2](https://spacefordeveloper.tistory.com/246)

**Comment by dongwonnn** [comment]
3/5 금요일 완료했습니다.

- [경주로 건설](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EA%B2%BD%EC%A3%BC%EB%A1%9C%20%EA%B1%B4%EC%84%A4.md)
- [기지국 설치](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EA%B8%B0%EC%A7%80%EA%B5%AD%20%EC%84%A4%EC%B9%98.md)
- [벽 부수고 이동하기2](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EB%B2%BD%20%EB%B6%80%EC%88%98%EA%B3%A0%20%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B02.md)
