### ISSUE TITLE
7차 코딩스터디(2/1~2/5)

### ISSUE THREAD

**Issue by LeeSeoYoung012** [LeeSeoYoung012/CodingStudy#7]
**7차 코딩스터디 (2/1~2/5)**
==============
**2/1 월요일**
------------------------
- Level2 피보나치 수  [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12945)
- Level2 순위 검색  [[Link]](https://programmers.co.kr/learn/courses/30/lessons/72412)
- [연산자 끼워넣기(2)](https://www.acmicpc.net/problem/15658)

2/2 화요일 
------------------------
- Level2  메뉴리뉴얼 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/72411)
- Level2  올바른 괄호 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/12909)
- [테트로미노](https://www.acmicpc.net/problem/14500)

2/3 수요일 
------------------------
- Level3 2Xn타일링[[Link]](https://programmers.co.kr/learn/courses/30/lessons/12900)
- Level3 브라이언의 고민[[Link]](https://programmers.co.kr/learn/courses/30/lessons/1830)
- [두 동전](https://www.acmicpc.net/problem/16197)

2/4 목요일 
------------------------
- Level3 풍선터트리기[[Link]](https://programmers.co.kr/learn/courses/30/lessons/68646)
- Level3 여행경로 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/43164)
- [에너지 모으기](https://www.acmicpc.net/problem/16198)

2/5 금요일 
-------------------------
- Level3  네트워크  [[Link]](https://programmers.co.kr/learn/courses/30/lessons/43162)
- Level3  섬 연결하기 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/42861)
- [N-Queen](https://www.acmicpc.net/problem/9663)

**Comment by inbdni** [comment]
2/1 월요일 완료했습니다.

* [피보나치 수](https://github.com/inbdni/Programmers/blob/master/level02/%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98%EC%88%98.cpp)
* [순위 검색 (효율성 실패)](https://github.com/inbdni/Programmers/blob/master/level02/%EC%88%9C%EC%9C%84%EA%B2%80%EC%83%89.cpp)
* [연산자 끼워넣기(2)](https://github.com/inbdni/Baekjoon/blob/master/15658_%EC%97%B0%EC%82%B0%EC%9E%90%EB%81%BC%EC%9B%8C%EB%84%A3%EA%B8%B02.cpp)

**Comment by LeeSeoYoung012** [comment]
2/1 월요일 완료했습니다.

* [피보나치 수](https://spacefordeveloper.tistory.com/161)
* [순위 검색 (효율성 실패)](https://spacefordeveloper.tistory.com/160)
* [연산자 끼워넣기(2)](https://spacefordeveloper.tistory.com/162)

**Comment by workhardslave** [comment]
2/1 월요일 완료했습니다.

- [피보나치 수](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%202/%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98%20%EC%88%98.cpp)
- 순위 검색(미해결)
- [연산자 끼워넣기 (2)](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/15658.cpp)

**Comment by Jiyoung-h** [comment]
2/1 월요일 완료했습니다.
- [피보나치 수](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98%EC%88%98.cpp)
- [순위 검색(미해결)](url)
- [연산자 끼워넣기 (2)](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/15658%EC%97%B0%EC%82%B0%EC%9E%90%20%EB%81%BC%EC%9B%8C%EB%84%A3%EA%B8%B0(2).cpp)

**Comment by Jiyoung-h** [comment]
2/2 화요일 완료했습니다.
- [메뉴리뉴얼(해결중)](url)
- [올바른 괄호](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%98%AC%EB%B0%94%EB%A5%B8%20%EA%B4%84%ED%98%B8.cpp)
- [테트로미노](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/14500%ED%85%8C%ED%8A%B8%EB%A1%9C%EB%AF%B8%EB%85%B8.cpp)

**Comment by inbdni** [comment]
2/2 화요일 완료했습니다.

* [메뉴리뉴얼(진행중)]()
* [올바른 괄호](https://github.com/inbdni/Programmers/blob/master/level02/%EC%98%AC%EB%B0%94%EB%A5%B8%EA%B4%84%ED%98%B8.cpp)
* [테트로미노](https://github.com/inbdni/Baekjoon/blob/master/14500_%ED%85%8C%ED%8A%B8%EB%A1%9C%EB%AF%B8%EB%85%B8.cpp)

**Comment by workhardslave** [comment]
2/2 화요일 완료했습니다.

- [메뉴 리뉴얼](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/%EC%B9%B4%EC%B9%B4%EC%98%A4/%EB%A9%94%EB%89%B4%20%EB%A6%AC%EB%89%B4%EC%96%BC.cpp)
- [올바른 괄호](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%202/%EC%98%AC%EB%B0%94%EB%A5%B8%20%EA%B4%84%ED%98%B8.cpp)
- [테트로미노](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/%EC%82%BC%EC%84%B1%20SW%20%EC%97%AD%EB%9F%89%20%ED%85%8C%EC%8A%A4%ED%8A%B8%20%EA%B8%B0%EC%B6%9C%20%EB%AC%B8%EC%A0%9C/14500(%EC%99%84%ED%83%90).cpp)

**Comment by dongwonnn** [comment]
2/2 화요일 완료했습니다.

- [피보나치 수](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98%20%EC%88%98.md)
- [순위 검색 ( 효율성 X )](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%88%9C%EC%9C%84%EA%B2%80%EC%83%89.md)
- [연산자 끼워넣기(2)](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EC%97%B0%EC%82%B0%EC%9E%90%20%EB%81%BC%EC%9B%8C%EB%84%A3%EA%B8%B0(2).md)
- [메뉴 리뉴얼 (진행중)](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%A9%94%EB%89%B4%EB%A6%AC%EB%89%B4%EC%96%BC.md)
- [올바른 괄호](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%98%AC%EB%B0%94%EB%A5%B8%20%EA%B4%84%ED%98%B8.md)
- [테크노미로](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%ED%85%8C%ED%81%AC%EB%85%B8%EB%AF%B8%EB%A1%9C.md)

**Comment by Jiyoung-h** [comment]
2/3 수요일 완료했습니다.
- [2Xn타일링](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/2%20x%20n%20%ED%83%80%EC%9D%BC%EB%A7%81.cpp)
- [브라이언의 고민](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%B8%8C%EB%9D%BC%EC%9D%B4%EC%96%B8%EC%9D%98%20%EA%B3%A0%EB%AF%BC.cpp)
- [두 동전](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16197%EB%91%90%20%EB%8F%99%EC%A0%84.cpp)

**Comment by workhardslave** [comment]
2/3 수요일 완료했습니다.

- [2 x n 타일링](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/2%20x%20n%20%ED%83%80%EC%9D%BC%EB%A7%81.cpp)
- 브라이언의 고민(미해결)
- [두 동전](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/16197%EB%B2%88.cpp)

**Comment by dongwonnn** [comment]
2/3 수요일 완료했습니다.
- [2 x n 타일링](https://github.com/dongwonnn/Algorithm/blob/master/programmers/2%20x%20n%20%ED%83%80%EC%9D%BC%EB%A7%81.md)
- 브라이언의 고민- JS 보류
- [두 동전](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EB%91%90%20%EB%8F%99%EC%A0%84.md)

**Comment by LeeSeoYoung012** [comment]
2/3 수요일 완료했습니다.
- [2 x n 타일링](https://spacefordeveloper.tistory.com/163)
- 브라이언의 고민(미해결)
- [두 동전](https://spacefordeveloper.tistory.com/165)

**Comment by inbdni** [comment]
2/3 수요일 완료했습니다.

* [2XN 타일링](https://github.com/inbdni/Programmers/blob/master/level03/2XN%ED%83%80%EC%9D%BC%EB%A7%81.cpp)
* [브라이언의 고민 (진행중)]()
* [두 동전](https://github.com/inbdni/Baekjoon/blob/master/16197_%EB%91%90%EB%8F%99%EC%A0%84.cpp)

**Comment by inbdni** [comment]
2/4 목요일 완료했습니다.

* [풍선 터트리기](https://github.com/inbdni/Programmers/blob/master/level03/%ED%92%8D%EC%84%A0%ED%84%B0%ED%8A%B8%EB%A6%AC%EA%B8%B0.cpp)
* [여행경로](https://github.com/inbdni/Programmers/blob/master/level03/%EC%97%AC%ED%96%89%EA%B2%BD%EB%A1%9C.cpp)
* [에너지 모으기](https://github.com/inbdni/Baekjoon/blob/master/16198_%EC%97%90%EB%84%88%EC%A7%80%EB%AA%A8%EC%9C%BC%EA%B8%B0.cpp)

**Comment by Jiyoung-h** [comment]
2/4 목요일 완료했습니다.
- [풍선 터트리기](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%ED%92%8D%EC%84%A0%20%ED%84%B0%ED%8A%B8%EB%A6%AC%EA%B8%B0.cpp)
- [여행경로](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%97%AC%ED%96%89%EA%B2%BD%EB%A1%9C.cpp)
- [에너지 모으기](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16198%EC%97%90%EB%84%88%EC%A7%80%20%EB%AA%A8%EC%9C%BC%EA%B8%B0.cpp)

**Comment by workhardslave** [comment]
2/4 목요일 완료했습니다

- [풍선 터트리기](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%ED%92%8D%EC%84%A0%20%ED%84%B0%ED%8A%B8%EB%A6%AC%EA%B8%B0.cpp)
- [여행경로](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EC%97%AC%ED%96%89%EA%B2%BD%EB%A1%9C.cpp)
- [에너지 모으기](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/16198.cpp)

**Comment by inbdni** [comment]
2/5 금요일 완료했습니다.

* [네트워크](https://github.com/inbdni/Programmers/blob/master/level03/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.cpp)
* [섬 연결하기](https://github.com/inbdni/Programmers/blob/master/level03/%EC%84%AC%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0.cpp)
* [N-Queen](https://github.com/inbdni/Baekjoon/blob/master/09663_N-Queen.cpp)

**Comment by Jiyoung-h** [comment]
2/5 금요일 완료했습니다.
- [네트워크](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.cpp)
- [섬 연결하기](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%84%AC%20%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0.cpp)
- [N-Queen](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/9663N-Queen.cpp)

**Comment by workhardslave** [comment]
2/5 금요일 완료했습니다.

- [네트워크](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.cpp)
- [섬 연결하기](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EC%84%AC%20%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0.cpp)
- [N-Queen](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/9663.cpp)

**Comment by LeeSeoYoung012** [comment]
2/4 목요일 완료했습니다

- [풍선 터트리기](https://spacefordeveloper.tistory.com/167)
- [여행경로](https://spacefordeveloper.tistory.com/166)
- [에너지 모으기](https://spacefordeveloper.tistory.com/168)

**Comment by LeeSeoYoung012** [comment]
2/5 금요일 완료했습니다.

- [네트워크](https://spacefordeveloper.tistory.com/171)
- [섬 연결하기](https://spacefordeveloper.tistory.com/169)
- [N-Queen](https://spacefordeveloper.tistory.com/170)

**Comment by dongwonnn** [comment]
2/5 금요일 완료했습니다.

- [네트워크](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.md)
- [섬 연결하기](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%84%AC%20%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0.md)
- [N-Queen](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/N-Queen.md)

**Comment by LeeSeoYoung012** [comment]
2/2 화요일 완료했습니다.

* [메뉴리뉴얼(진행중)]()
* [올바른 괄호](https://spacefordeveloper.tistory.com/177)
* [테트로미노](https://spacefordeveloper.tistory.com/178)

**Comment by dongwonnn** [comment]
2/4 목요일 완료했습니다.

- [풍선 터트리기](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%ED%92%8D%EC%84%A0%ED%84%B0%ED%8A%B8%EB%A6%AC%EA%B8%B0.md)
- [여행경로](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%97%AC%ED%96%89%20%EA%B2%BD%EB%A1%9C.md)
- [에너지 모으기](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EC%97%90%EB%84%88%EC%A7%80%EB%AA%A8%EC%9C%BC%EA%B8%B0.md)
