### ISSUE TITLE
8차 코딩스터디(2/8~2/12)

### ISSUE THREAD

**Issue by LeeSeoYoung012** [LeeSeoYoung012/CodingStudy#8]
**8차 코딩스터디 (2/8~2/12)**
==============
**2/8 월요일**
------------------------
- Level3 단어변환  [[Link]](https://programmers.co.kr/learn/courses/30/lessons/43163)
- Level3 가장 먼 노드  [[Link]](https://programmers.co.kr/learn/courses/30/lessons/49189)
- [뱀과 사다리게임](https://www.acmicpc.net/problem/16928)

2/9 화요일 
------------------------
- Level3  디스크 컨트롤러 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/42627)
- Level3  단속카메라 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/42884)
- [데스 나이트](https://www.acmicpc.net/problem/16948)

2/10 수요일 
------------------------
- Level3 이중우선순위큐 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/42628)
- Level3 입국심사 [[Link]](https://programmers.co.kr/learn/courses/30/lessons/43238)
- [연구소](https://www.acmicpc.net/problem/14502)

2/11 목요일 
------------------------
설날

2/12 금요일 
-------------------------
설날

**Comment by inbdni** [comment]
2/8 월요일 완료했습니다.

* [단어 변환](https://github.com/inbdni/Programmers/blob/master/level03/%EB%8B%A8%EC%96%B4%EB%B3%80%ED%99%98.cpp)
* [가장 먼 노드](https://github.com/inbdni/Programmers/blob/master/level03/%EA%B0%80%EC%9E%A5%EB%A8%BC%EB%85%B8%EB%93%9C.cpp)
* [뱀과 사다리 게임](https://github.com/inbdni/Baekjoon/blob/master/16928_%EB%B1%80%EA%B3%BC%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%B2%8C%EC%9E%84.cpp)

**Comment by dongwonnn** [comment]
2/8 월요일 완료했습니다.

- [단어 변환](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%8B%A8%EC%96%B4%20%EB%B3%80%ED%99%98.md)
- [가장 먼 노드](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EA%B0%80%EC%9E%A5%20%EB%A8%BC%20%EB%85%B8%EB%93%9C.md)
- [뱀과 사다리 게임](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EB%B1%80%EA%B3%BC%20%EC%82%AC%EB%8B%A4%EB%A6%AC%20%EA%B2%8C%EC%9E%84.md)

**Comment by workhardslave** [comment]
2/8 월요일 완료했습니다.

- [단어 변환](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EB%8B%A8%EC%96%B4%20%EB%B3%80%ED%99%98.cpp)
- [가장 먼 노드](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EA%B0%80%EC%9E%A5%20%EB%A8%BC%20%EB%85%B8%EB%93%9C.cpp)
- [뱀과 사다리 게임](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/16928.cpp)

**Comment by Jiyoung-h** [comment]
2/8 월요일 완료했습니다.
- [단어 변환](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%8B%A8%EC%96%B4%EB%B3%80%ED%99%98.cpp)
- [가장 먼 노드](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EA%B0%80%EC%9E%A5%20%EB%A8%BC%20%EB%85%B8%EB%93%9C.cpp)
- [뱀과 사다리 게임](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16928%EB%B1%80%EA%B3%BC%20%EC%82%AC%EB%8B%A4%EB%A6%AC%20%EA%B2%8C%EC%9E%84.cpp)

**Comment by LeeSeoYoung012** [comment]
2/8 월요일 완료했습니다.
- [단어 변환](https://spacefordeveloper.tistory.com/186)
- [단속카메라](https://spacefordeveloper.tistory.com/187)
- [뱀과 사다리 게임](https://spacefordeveloper.tistory.com/188)

**Comment by Jiyoung-h** [comment]
2/9 화요일 완료했습니다.
- [디스크 컨트롤러](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%94%94%EC%8A%A4%ED%81%AC%20%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC.cpp)
- [단속카메라](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EB%8B%A8%EC%86%8D%EC%B9%B4%EB%A9%94%EB%9D%BC.cpp)
- [데스 나이트](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/16948%EB%8D%B0%EC%8A%A4%20%EB%82%98%EC%9D%B4%ED%8A%B8.cpp)

**Comment by inbdni** [comment]
2/9 화요일 완료했습니다.

* [디스크 컨트롤러](https://github.com/inbdni/Programmers/blob/master/level03/%EB%94%94%EC%8A%A4%ED%81%AC%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC.cpp)
* [단속카메라](https://github.com/inbdni/Programmers/blob/master/level03/%EB%8B%A8%EC%86%8D%EC%B9%B4%EB%A9%94%EB%9D%BC.cpp)
* [데스 나이트](https://github.com/inbdni/Baekjoon/blob/master/16948_%EB%8D%B0%EC%8A%A4%EB%82%98%EC%9D%B4%ED%8A%B8.cpp)

**Comment by workhardslave** [comment]
2/9 화요일 완료했습니다.

- [디스크 컨트롤러](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EB%94%94%EC%8A%A4%ED%81%AC%20%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC.cpp)
- [단속카메라](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EB%8B%A8%EC%86%8D%EC%B9%B4%EB%A9%94%EB%9D%BC.cpp)
- [데스 나이트](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/DFS%26BFS%26%EC%99%84%EC%A0%84%ED%83%90%EC%83%89%26%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98(%EA%B5%AC%ED%98%84)/16948.cpp)

**Comment by dongwonnn** [comment]
2/9 화요일 완료했습니다.

- 디스크 컨트롤러 ( 진행중 )
- [단속카메라](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EB%8B%A8%EC%86%8D%EC%B9%B4%EB%A9%94%EB%9D%BC.md)
- [데스 나이트](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EB%8D%B0%EC%8A%A4%EB%82%98%EC%9D%B4%ED%8A%B8.md)

**Comment by LeeSeoYoung012** [comment]
2/10 수요일 완료했습니다.
- [Level3 이중우선순위큐](https://spacefordeveloper.tistory.com/189)
- [Level3 입국심사](https://spacefordeveloper.tistory.com/190) 
- [연구소](https://spacefordeveloper.tistory.com/191)

**Comment by Jiyoung-h** [comment]
2/10 수요일 완료했습니다.
- [이중우선순위큐](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%9D%B4%EC%A4%91%EC%9A%B0%EC%84%A0%EC%88%9C%EC%9C%84%ED%81%90.cpp)
- [입국심사](https://github.com/Jiyoung-h/algorithm/blob/main/programmers/%EC%9E%85%EA%B5%AD%EC%8B%AC%EC%82%AC.cpp)
- [연구소](https://github.com/Jiyoung-h/algorithm/blob/main/baekjoon/14502%EC%97%B0%EA%B5%AC%EC%86%8C.cpp)

**Comment by dongwonnn** [comment]
2/10 수요일 완료했습니다.

- [이중우선 순위큐](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%9D%B4%EC%A4%91%EC%9A%B0%EC%84%A0%EC%88%9C%EC%9C%84%ED%81%90)
- [입국심사](https://github.com/dongwonnn/Algorithm/blob/master/programmers/%EC%9E%85%EA%B5%AD%EC%8B%AC%EC%82%AC.md)
- [연구소](https://github.com/dongwonnn/Algorithm/blob/master/backjoon/%EC%97%B0%EA%B5%AC%EC%86%8C.md)

**Comment by workhardslave** [comment]
2/10 수요일 완료했습니다. 다들 설 연휴 잘 보내세요

- [이중우선순위큐](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EC%9D%B4%EC%A4%91%EC%9A%B0%EC%84%A0%EC%88%9C%EC%9C%84%ED%81%90.cpp)
- [입국심사](https://github.com/workhardslave/PS/blob/master/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Level%203/%EC%9E%85%EA%B5%AD%EC%8B%AC%EC%82%AC.cpp)
- [연구소](https://github.com/workhardslave/PS/blob/master/%EB%B0%B1%EC%A4%80/%EC%82%BC%EC%84%B1%20SW%20%EC%97%AD%EB%9F%89%20%ED%85%8C%EC%8A%A4%ED%8A%B8%20%EA%B8%B0%EC%B6%9C%20%EB%AC%B8%EC%A0%9C/14502.cpp)

**Comment by inbdni** [comment]
2/10 수요일 완료했습니다. 연휴 잘 보내세요 :-)

* [이중우선순위큐](https://github.com/inbdni/Programmers/blob/master/level03/%EC%9D%B4%EC%A4%91%EC%9A%B0%EC%84%A0%EC%88%9C%EC%9C%84%ED%81%90.cpp)
* [입국심사](https://github.com/inbdni/Programmers/blob/master/level03/%EC%9E%85%EA%B5%AD%EC%8B%AC%EC%82%AC.cpp)
* [연구소](https://github.com/inbdni/Baekjoon/blob/master/14502_%EC%97%B0%EA%B5%AC%EC%86%8C.cpp)

**Comment by LeeSeoYoung012** [comment]
2/9 화요일 완료했습니다.
- [디스크 컨트롤러](https://spacefordeveloper.tistory.com/193)
- [가장 먼 노드](https://spacefordeveloper.tistory.com/194)
- [데스 나이트](https://spacefordeveloper.tistory.com/195)
